# Generated by Django 4.2.20 on 2025-04-11 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_alter_reportinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
