# Generated by Django 4.2.20 on 2025-04-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_reportinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='log_level',
            field=models.CharField(choices=[('info', 'Info'), ('error', 'Error')], default='info', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='step',
            field=models.CharField(choices=[('extract', 'Extract'), ('transform', 'Transform'), ('load', 'Load'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
